#include <iostream>
#include <utility>
#include <vector>
#include <memory>
#include <string>
#include <sstream>
#include <limits>
#include "carManufacturing/info/CarInfoDisplay.h"
#include "include/carManufacturing/CarCosts.h"
#include "include/carManufacturing/CommercialCar.h"
#include "include/marketing/Customer.h"
#include "include/marketing/FreeAdvertisementDisplay.h"
#include "include/marketing/PaidAdvertisementDisplay.h"
#include "include/assembly-line/Product.h"
#include "include/assembly-line/builder/CarBuilder.h"
#include "include/assembly-line/builder/SportsCarBuilder.h"
#include "include/assembly-line/builder/OffroadCarBuilder.h"
#include "include/assembly-line/builder/ElectricCarBuilder.h"
#include "include/assembly-line/Assembly.h"
#include "include/carManufacturing/factory/SedanFactory.h"
#include "include/carManufacturing/factory/SUVFactory.h"
#include "include/carManufacturing/CarDecorator.h"
#include "include/carManufacturing/TunedCarDecorator.h"
#include "carManufacturing/actions/OffroadCar.h"
#include "carManufacturing/actions/SedanActions.h"
#include "carManufacturing/actions/SUVActions.h"
#include "include/personnel/Worker.h"
#include "include/personnel/Supervisor.h"
#include "include/user/Menu.h"
#include "include/marketing/notification/Notification.h"
#include "include/marketing/notification/Advertiser.h"
#include "include/marketing/notification/ConcreteObserver.h"
#include "include/carManufacturing/info/DetailedCarInfo.h"
#include "include/carManufacturing/info/SummaryCarInfo.h"
